### PR TITLE
drop Scala 2.11 support and add Scala 2.13.0 cross-build for everything but the diode-react sub-project

### PR DESCRIPTION
**Pull request by russwyte**
Supporting: #86

This is just a suggestion for how to support 2.13.0 in at least the diode-core and diode-data sub-projects.

Unfortunately because of the utest dependency I had to drop scala 2.11 crossVersion.

### CODE REVIEW

**Comment by erinmez** [comment]
@ochrons, I would love to transition to 2.13.x too, for io.suzaku.diode & io.suzaku.diode-devtools. Could this be merged perhaps?

**Comment by erinmez** [comment]
@ochrons, could an "official" release be made with this? (scala is now at 2.13.1 & scalajs at 0.6.31)

**Comment by russwyte** [comment]
@ochrons I am curious as well - is there something missing to get this to a maven release?

BTW - I am working on SJS 1.0.x support as well, but that will be a new PR.

**Comment by ochrons** [comment]
Nah, it's just my laziness 😅 

I'll push a release out this weekend!

**Comment by ochrons** [comment]
Ok, 1.1.6 is finally published and on its way to Maven central. Thanks for your help and patience!

**Comment by erinmez** [comment]
Thanks a lot!

**Pull request merged**
