### PR TITLE
Return equality test directly

### PR DESCRIPTION
**Pull request by adrienhaxaire**
Hello, a little refactoring you might want.

### CODE REVIEW

**Comment by adrienhaxaire** [comment]
I see that this test is failing:
```
X diode.CircuitJVMTests.SequenceActionEffects 319ms 
  utest.AssertionError: assert(c.model.list != Vector.range(0, 1000))
  c: diode.CircuitJVMTests.TestCircuit = diode.CircuitJVMTests$TestCircuit@22c67b7
    utest.asserts.Asserts$.assertImpl(Asserts.scala:30)
    diode.CircuitJVMTests$.$anonfun$tests$27(CircuitJVMTests.scala:111)
```
I don't understand why, I continue investigating.

**Comment by adrienhaxaire** [comment]
This time the test passed, maybe we could look into improving the test or the runner?

**Comment by cquiroz** [comment]
thanks for this. Indeed one of the tests fails form time to time but I haven't been able to isolate it

**Review by cquiroz — APPROVED** [review]
LGTM

**Comment by adrienhaxaire** [comment]
Thanks!

**Pull request merged**
