### PR TITLE
Upgrade ScalaJS-React

### PR DESCRIPTION
**Pull request by alonsodomin**
Upgrades the react module to work with latest version of ScalaJS-React (v1.2.0)

### CODE REVIEW

**Comment by ochrons** [comment]
Is there something in the connector that doesn't work with SJS-React 1.2.0?

**Comment by alonsodomin** [comment]
yeah, some types have changed and that produces a series of linkage errors when generating the JavaScript.

The one that really affects Diode is the fact that `BackendScope` now becomes a type alias for an always mounted component's backend, and this means that the method `isMounted` disappears.

**Comment by ochrons** [comment]
Ok, LGTM!

**Comment by SakulK** [comment]
When is a new version of diode with this pull request going to be released? :)

**Pull request merged**
